FROM r-base

LABEL author="AnalyticsEarth"

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y libssl-dev \
  && apt-get clean

ADD https://www.rforge.net/Rserve/snapshot/Rserve_1.8-6.tar.gz .
RUN R CMD INSTALL Rserve_1.8-6.tar.gz

COPY runservice-rserve.sh runservice-rserve.sh

EXPOSE 6311/tcp

ENTRYPOINT runservice-rserve.sh
