FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder

LABEL author="AnalyticsEarth"

# Details
LABEL version="2.0.0"
LABEL description="SSEtoRserve on dotnetcore with self spawning R instance"

RUN mkdir -p /root/src/app/sse2rserve
WORKDIR /root/src/app/sse2rserve

COPY SSEtoRServeCore/SSEtoRServeCore.csproj SSEtoRServeCore/SSEtoRServeCore.csproj
RUN dotnet restore SSEtoRServeCore/SSEtoRServeCore.csproj

COPY SSEtoRServeCore/ .
RUN dotnet publish -c release -r linux-x64 -o published

FROM mcr.microsoft.com/dotnet/core/runtime:3.1

RUN groupadd -r sse2rserve \
 && useradd -g sse2rserve --create-home --shell /bin/bash sse2rserve

WORKDIR /root/
COPY --from=builder /root/src/app/sse2rserve/published .
RUN chown sse2rserve:sse2rserve . && \
  chmod +x -R .

EXPOSE 50051/tcp
EXPOSE 19345/tcp
USER sse2rserve
CMD dotnet ./SSEtoRServeCore.dll
